---
apiVersion: v2
name: memcached-operator
description: A Helm chart for the Memcached Kubernetes Operator (memcached.c5c3.io)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/c5c3/memcached-operator
sources:
  - https://github.com/c5c3/memcached-operator
maintainers:
  - name: c5c3
    url: https://github.com/c5c3
keywords:
  - memcached
  - operator
  - kubernetes
  - cache
