version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/c5c3/memcached-operator

linters:
  exclusions:
    paths:
      - bin
      - testbin
      - hack
    rules:
      - linters:
          - gocyclo
        path: _test\.go
  enable:
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
