# Planwerk Configuration

[planwerk]
id_prefix = "MO"

[project]
type = "go-project"
name = "memcached-operator"

[external_review]
enabled = true
auto_request = true

[prompts]
push_enabled = false

[git]
author = "Christian Berendt <berendt@23technologies.cloud>"
co_author = ""
trailers = [
    "AI-assisted: Claude Code",
]

[[git.users]]
github_account = "berendt"
name = "Christian Berendt"
email = "berendt@23technologies.cloud"
trailers = [
    "On-behalf-of: @SAP christian.berendt@sap.com",
    "Signed-off-by: Christian Berendt <berendt@23technologies.cloud>"
]
